services:
  postgres:
    build:
      context: .
      dockerfile: ./pg/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: linkyhost
    network_mode: host
    volumes:
      - ./pg/data:/var/lib/postgresql/data
      - ./pg/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    restart: unless-stopped
    command: server --address ":9671" --console-address ":9670" /data1
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "2"
          memory: 2G
    volumes:
      - ./minio/data1:/data1:delegated
      - ./minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=linkyhost_minio
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9671/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  createbuckets:
    image: minio/mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://127.0.0.1:9671 minioadmin linkyhost_minio; /usr/bin/mc mb myminio/linkyhost; exit 0; "
      
